#!/bin/sh

SESSION="upgrades"

# Homebrew
tmux -2 new-session -d -s $SESSION -n 'brew'
tmux send-keys "bru" C-m

# Neovim
tmux new-window -t $SESSION:2 -n 'neovim'
tmux send-keys "nvim +PlugUpgrade +PlugUpdate ! +qall" C-m

# set default window
tmux select-window -t $SESSION:1

# attach to session
tmux -2 attach-session -t $SESSION
