#!/bin/sh
#
# bootstrap
#
# Install dependencies.

# Inspired heavily by davidxia's bootstrap_dotfiles
#   URL: https://github.com/davidxia/bootstrap_dotfiles/


die () {
    echo "Error: $1"
    exit 1
}


echo_with_color () {
    echo "\033[0;34m$1\033[0m"
}


install_homebrew () {
    echo_with_color "\nChecking if homebrew is already installed..."
    if [ -x /usr/local/bin/brew ] ; then
        echo "Homebrew is already installed."
    else
        die "Homebrew not installed."
    fi
}


install_homebrew_pkgs () {
    echo_with_color "\nInstalling homebrew packages..."
    brew install ack
    brew install coreutils
    brew install git git-extras
    brew install macvim --override-system-vim
    brew install --disable-etcdir zsh
    brew install z
}


install_vundle () {
    echo_with_color "\nChecking if vundle is already installed..."

    # create vundle directory
    if [ ! -d ~/.vim/bundle/vundle/ ] ; then
        mkdir -p ~/.vim/bundle/vundle
    fi
    
    # install vundle
    if [ ! -d ~/.vim/bundle/vundle/.git/ ] ; then
        echo "Vundle not installed. Installing now..."
        git clone http://github.com/gmarik/vundle.git ~/.vim/bundle/vundle
    else
        echo "Vundle is already installed."
    fi
}


install_vundle_pkgs () {
    echo_with_color "\nInstalling vundle packages..."

    # check that vim is installed
    if test ! $(which vim) ; then
        die "Vim not installed."
    fi

    # install packages
    vim -c "execute \"BundleInstall\" | q | q"
}


# OS-specific settings
if [ $(uname -s) = "Darwin" ] ; then
    install_homebrew
    install_homebrew_pkgs 
fi


# install all other dependencies
install_vundle
install_vundle_pkgs
