#!/bin/sh
#
# Usage: script/bootstrap
#
# Install dependencies.

# Inspired bootstrap install scripts from:
#   davidxia's dotfiles (https://github.com/davidxia/bootstrap_dotfiles/)
#   joshdick's dotfiles (https://github.com/joshdick/dotfiles)



# Error (red, underlined)
msg_fail () {
  printf "\033[0;31;4mError\033[0m: $1 \n"
  exit 1
}


# Text (blue)
msg_run () {
  printf "\n\033[0;34m$1\033[0m \n"
}


# check if cmd exists
exists () {
  command -v "$1" >/dev/null 2>&1
}


install_dotfiles () {
  msg_run "Installing dotfiles to $HOME ..."    

  # get path of dotfiles repo
  DOTFILES_ROOT="$( cd "$( dirname "$0" )" && cd .. && pwd )"

  # set global default install options
  skip_all=false
  overwrite_all=false
  backup_all=false

  # get list of all dotfiles to be symlinked
  # NOTE: assumes a dotfiles structure of topic/setting.symlink
  #       (e.g. zsh/zshrc.symlink)
  for file in `find $DOTFILES_ROOT -maxdepth 2 -name \*.symlink` ; do

    # get filename of $file (no path)
    symlink_filename=`basename "$file"`

    # create absolute path for link target
    target=`echo "$HOME/.$symlink_filename" | sed "s/\.symlink$//g"`

    # target basename
    target_name=`basename "$target"`
        
    # set default install options (per symlink file)
    skip=false
    overwrite=false
    backup=false

    # get user input if dotfiles already exist
    if [ -f $target ] || [ -d $target ] ; then
    
      if [ "$overwrite_all" = "false" ] && [ "$backup_all" = "false" ] \
        && [ "$skip_all" = "false" ] ; then 
            
        # get user input 
        printf "\033[0;31;4mError\033[0m: $target_name already exists:" 
        printf " [s]kip," 
        printf " [S]kip all," 
        printf " [o]verwrite,"
        printf " [O]verwrite all,"
        printf " [b]ackup,"
        printf " [B]ackup all? \n"
        read REPLY
        
        # apply user input 
        case "$REPLY" in
          s) skip=true ;; 
          S) skip_all=true ;;
          o) overwrite=true ;; 
          O) overwrite_all=true ;; 
          b) backup=true ;; 
          B) backup_all=true ;; 
          *) msg_fail "unknown option; quitting now ..." ;;
        esac
      fi # end if-statement for if no global options are set
            
      # delete pre-existing dotfiles
      if [ "$overwrite" = "true" ] || [ "$overwrite_all" = "true" ] ; then
        printf "Overwriting $target_name ... \n"
        rm -rf $target
      fi

      # backup pre-existing dotfiles
      if [ "$backup" = "true" ] || [ "$backup_all" = "true" ] ; then
        printf "Backing up $target_name ... \n"
        mv $target $target\.backup
      fi
    
      # linking dotfiles
      if [ "$skip" = "false" ] && [ "$skip_all" = "false" ] ; then
        ln -s $file $target
      else
        printf "Skipping $target_name ... \n"
      fi
    
    # link dotfiles if they don't already exist 
    else
      printf "Installing $target_name ... \n"
      ln -s $file $target
    fi

  done # end loop for all *.symlink files

}


install_homebrew_pkgs () {

  if ! exists brew ; then
    echo ""
    msg_fail "Homebrew not installed; unable to continue ..."
  fi

  # update homebrew package list (silently)
  brew update >/dev/null 2>&1

  # git 
  msg_run "Installing Git, for version control ..."
    brew install git 
    brew install git-extras

  # shells
  msg_run "Installing ZSH, a better shell than BASH ..."
    brew install --disable-etcdir zsh

  # editors
  msg_run "Install Vim ..."
    brew install vim --override-system-vim

  msg_run "Installing MacVim, a nice Vim GUI ..."
    brew install macvim

  # tools
  msg_run "Installing The Silver Searcher, (better than ack or grep) for searching the contents of files ..."
    brew install the_silver_searcher

  msg_run "Installing coreutils, a collection of GNU utilities ..."
    brew install coreutils

  # languages
  msg_run "Installing Python ..."
    brew install python
  
  msg_run "Installing Ruby ..."
    brew install ruby 

  # tmux
  msg_run "Installing tmux ..."
    brew install tmux

}


install_vim_pkgs () {

  if [ ! -d $HOME/.vim/bundle/vundle/ ] ; then
    msg_run "Installing Vundle, a good Vim package manager ..."
    git clone http://github.com/gmarik/vundle.git $HOME/.vim/bundle/vundle
  fi

  msg_run "Installing Vim packages ..."
  if exists vim ; then 
    vim +BundleInstall +qall >/dev/null 2>&1
  elif exists mvim ; then 
    mvim +BundleInstall +qall >/dev/null 2>&1
  else
    msg_fail "Vim not installed."
  fi
}


install_dotfiles

# OS-specific installs
if [ $(uname -s) = "Darwin" ] ; then
  msg_run "Install dependencies? [Y/N] "
  read REPLY

  case "$REPLY" in
    [yY]) 
      install_homebrew_pkgs ;;
    [nN]) 
      printf "Skipping dependency install ... \n" ;;
    *) 
      msg_fail "unknown option; quitting now ..." ;;
  esac
fi

install_vim_pkgs

msg_run "Finished!"
printf "To apply changes, reload ZSH using '. ~/.zshrc' ... \n"

exit 0

# vim: autoindent tabstop=2 shiftwidth=2 expandtab softtabstop=2 filetype=sh
